-- GENERATED by C->Haskell Compiler, version 0.18.2 The shapeless maps, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue103.chs" #-}
module Main where

import Foreign.C.Types


import Issue103A
{-# LINE 6 "Issue103.chs" #-}


testFunc :: (TestEnum) -> IO ()
testFunc a1 =
  let {a1' = (fromIntegral . fromEnum) a1} in 
  testFunc'_ a1' >>
  return ()

{-# LINE 8 "Issue103.chs" #-}


main :: IO ()
main = do
  testFunc E1
  testFunc E2
  testFunc E3

foreign import ccall unsafe "Issue103.chs.h test_func"
  testFunc'_ :: (CInt -> (IO ()))
