-- GENERATED by C->Haskell Compiler, version 0.18.2 The shapeless maps, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue103A.chs" #-}
module Issue103A where

import Foreign.C.Types



data TestEnum = E1
              | E2
              | E3
  deriving (Enum)

{-# LINE 7 "Issue103A.chs" #-}

