-- GENERATED by C->Haskell Compiler, version 0.18.2 The shapeless maps, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue97.chs" #-}
-- Main.chs
{-# LANGUAGE ForeignFunctionInterface #-}
module Main where

import Issue97A
{-# LINE 5 "Issue97.chs" #-}

import Foreign
import Foreign.C.Types



fooX :: (FooPtr) -> (Int)
fooX a1 =
  let {a1' = id a1} in 
  let {res = fooX'_ a1'} in
  let {res' = fromIntegral res} in
  (res')

{-# LINE 11 "Issue97.chs" #-}


main :: IO ()
main = allocaBytes 8 $ \fooPtr -> do
    (\ptr val -> do {pokeByteOff ptr 0 (val::CInt)}) fooPtr 42
    print $ fooX fooPtr

foreign import ccall safe "Issue97.chs.h foo_x"
  fooX'_ :: ((FooPtr) -> CInt)
