-- GENERATED by C->Haskell Compiler, version 0.18.2 The shapeless maps, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue97A.chs" #-}
-- Foo.chs
{-# LANGUAGE EmptyDataDecls, ForeignFunctionInterface #-}
module Issue97A (
      Foo
    , FooPtr
    ) where

import Foreign



data Foo
type FooPtr = Ptr (Foo)
{-# LINE 13 "Issue97A.chs" #-}

