-- GENERATED by C->Haskell Compiler, version 0.20.1 The shapeless maps, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue46.chs" #-}
module Main where



newtype Oid = Oid (ForeignPtr (Oid))
withOid :: Oid -> (Ptr Oid -> IO b) -> IO b
withOid (Oid fptr) = withForeignPtr fptr
{-# LINE 5 "Issue46.chs" #-}


func :: (Oid) -> (Int) -> (Float) -> IO ((Oid))
func a1 a2 a3 =
  (withOid) a1 $ \a1' -> 
  let {a2' = fromIntegral a2} in 
  let {a3' = realToFrac a3} in 
  func'_ a1' a2' a3' >>= \res ->
  (newForeignPtr_ >=> (return . Oid)) res >>= \res' ->
  return (res')

{-# LINE 7 "Issue46.chs" #-}


foreign import ccall safe "Issue46.chs.h func"
  func'_ :: ((Ptr (Oid)) -> (CInt -> (CFloat -> (IO ()))))
