-- GENERATED by C->Haskell Compiler, version 0.26.2 Budburst, 26 October 2015 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue152.chs" #-}
module Main where





f, g :: Int
f = 4
{-# LINE 6 "Issue152.chs" #-}

g = 4
{-# LINE 7 "Issue152.chs" #-}


main :: IO ()
main = putStrLn "OK"
