-- GENERATED by C->Haskell Compiler, version 0.23.1 Snowbounder, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue127.chs" #-}
module Main where

import Foreign
import Foreign.C.Types



tst :: (Int) -> IO ((Bool))
tst a1 =
  let {a1' = fromIntegral a1} in 
  tst'_ a1' >>= \res ->
  let {res' = toBool res} in
  return (res')

{-# LINE 8 "Issue127.chs" #-}


main :: IO ()
main = do
  tst 5 >>= print
  tst (-2) >>= print

foreign import ccall safe "Issue127.chs.h tst"
  tst'_ :: (CInt -> (IO CUChar))
