-- GENERATED by C->Haskell Compiler, version 0.18.2 The shapeless maps, 31 Oct 2014 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "Issue65.chs" #-}
module Main where



const1 :: Int
const1 = 123
{-# LINE 6 "Issue65.chs" #-}


const2 :: Double
const2 = 3.14
{-# LINE 9 "Issue65.chs" #-}


const3 :: String
const3 = "hello"
{-# LINE 12 "Issue65.chs" #-}


main :: IO ()
main = print const1 >> print const2 >> print const3
